/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Healthz */
        get: operations["healthz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Projects */
        get: operations["list_projects"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project}/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Summary */
        get: operations["summary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project}/waves": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Waves */
        get: operations["waves"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project}/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Tasks */
        get: operations["list_tasks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project}/tasks/{task_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Task */
        get: operations["get_task"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project}/tasks/{task_id}/candidates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Candidates
         * @description Per-candidate detail: the checkpoint when there is one, else the event log.
         *
         *     The checkpoint is authoritative and live (it holds the attempt currently
         *     running); the events fallback is history for a task whose checkpoint was
         *     pruned or which ran before the panel existed. `source` tells the UI which it
         *     got, because only the checkpoint can show an in-flight attempt.
         */
        get: operations["get_candidates"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project}/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Runs */
        get: operations["list_runs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project}/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run */
        get: operations["get_run"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project}/usage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Usage */
        get: operations["usage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project}/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Metrics */
        get: operations["metrics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Events */
        get: operations["list_events"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project}/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Jobs */
        get: operations["list_jobs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project}/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job */
        get: operations["get_job"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project}/jobs/{job_id}/log": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job Log */
        get: operations["get_job_log"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project}/jobs/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start Run */
        post: operations["start_run"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project}/jobs/plan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start Plan */
        post: operations["start_plan"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project}/jobs/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start Resume */
        post: operations["start_resume"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project}/jobs/import-backlog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start Import Backlog */
        post: operations["start_import_backlog"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project}/jobs/reconcile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start Reconcile
         * @description Close out runs whose process died without writing a terminal status.
         *
         *     Free and confirm-less, like `import-backlog`: it calls no provider and touches
         *     no git. It writes to the store, which is exactly why it is a spawned CLI job
         *     rather than an API-side update — the API stays read-only (PLAN §3.1 rule 2).
         */
        post: operations["start_reconcile"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project}/jobs/{job_id}/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Stop Job
         * @description SIGINT → grace → SIGTERM → grace → SIGKILL, then the final record.
         *
         *     Async, and awaited rather than backgrounded, because the answer the UI needs
         *     is what the job actually did — a 202 "stopping" would leave the console
         *     guessing. Stopping an already-finished job is a no-op returning its record,
         *     not an error: the poll that raced the exit is the common case.
         */
        post: operations["stop_job"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project}/discuss": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Discuss */
        get: operations["get_discuss"];
        put?: never;
        /** Start Discuss */
        post: operations["start_discuss"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project}/discuss/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Close Discuss
         * @description Abort and close. The transcript is already persisted, so history survives.
         */
        delete: operations["close_discuss"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project}/discuss/{session_id}/reply": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reply
         * @description Answer the pending question, or decide at the preview (`y`/`edit`/`abort`).
         *
         *     409 rather than a queue when nothing is pending: a reply typed before the
         *     planner asked would silently become the answer to whatever it asks next.
         */
        post: operations["reply"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project}/discuss/{session_id}/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stream Discuss */
        get: operations["stream_discuss"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project}/discuss/{session_id}/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Update Settings
         * @description Change the session's tunables. Takes effect on the next planner turn —
         *     including one already being composed, since the loop re-reads at the top.
         */
        post: operations["update_settings"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project}/discuss/{session_id}/pins": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload Pin
         * @description Put a file the operator sent in front of the planner, from the next turn on.
         *
         *     No `require_repo_path`: a pin is content, never a location, so there is no
         *     path to resolve and nothing is read from disk.
         */
        post: operations["upload_pin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project}/discuss/{session_id}/pins/remove": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Remove Pin
         * @description Unpin. A POST rather than a DELETE because the display path is a body
         *     field: a name with slashes in it cannot travel in a path segment.
         */
        post: operations["remove_pin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project}/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stream */
        get: operations["stream"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ApiError
         * @description FastAPI's `HTTPException` envelope: a single human-readable string.
         */
        ApiError: {
            /**
             * Detail
             * @description human-readable reason; safe to show verbatim
             */
            detail: string;
        };
        /** Candidate */
        Candidate: {
            /** Cand Id */
            cand_id: string;
            /** Attempt */
            attempt: number;
            /**
             * Status
             * @description gate_passed | gate_failed | patch_failed | llm_failed | visual_failed | visual_unverifiable | skipped
             */
            status?: string | null;
            /** Model */
            model?: string | null;
            /** Branch */
            branch?: string | null;
            /** Worktree */
            worktree?: string | null;
            /**
             * No Patch
             * @default false
             */
            no_patch: boolean;
            /** Error */
            error?: string | null;
            /**
             * Gate Log
             * @description tail only, never the full log
             */
            gate_log?: string | null;
            /** Notes */
            notes?: string | null;
            /**
             * Has Diff
             * @default false
             */
            has_diff: boolean;
            /** Visual Facts */
            visual_facts?: {
                [key: string]: unknown;
            } | null;
        };
        /** Candidates */
        Candidates: {
            /** Task Id */
            task_id: string;
            /**
             * Run Id
             * @description run whose thread was read
             */
            run_id?: string | null;
            /**
             * Source
             * @enum {string}
             */
            source: "checkpoint" | "events" | "none";
            /** Candidates */
            candidates: components["schemas"]["Candidate"][];
        };
        /** ChannelTotals */
        ChannelTotals: {
            /** Calls */
            calls: number;
            /** In Tok */
            in_tok: number;
            /** Out Tok */
            out_tok: number;
            /** Cache Hit */
            cache_hit: number;
            /** Cache Miss */
            cache_miss: number;
            /**
             * Cost
             * @description USD; real for cash, notional quota for subscription
             */
            cost: number;
        };
        /**
         * DiscussFrame
         * @description One event from the loop. `seq` is the replay cursor: reconnect with
         *     `?since=<seq>` and the stream resumes exactly where it stopped.
         */
        DiscussFrame: {
            /** Seq */
            seq: number;
            /** Ts */
            ts: number;
            /** Kind */
            kind: ("you" | "thinking" | "progress" | "assumption" | "question" | "awaiting" | "note" | "specs_preview" | "applied" | "aborted" | "turn_failed" | "limit_paused" | "error" | "closed") | string;
            /**
             * Data
             * @description kind-dependent: `question` carries id/q/why, `specs_preview` carries the proposed specs, `you` carries text, `progress` carries phase/tool/target/text while a turn runs, `turn_failed` carries text, and `limit_paused` carries text/resets_at/limit_type/seconds
             */
            data: {
                [key: string]: unknown;
            };
        };
        /**
         * DiscussOptions
         * @description What this project's config actually permits, so the settings UI offers
         *     real choices instead of a hardcoded list that can drift from the harness.
         */
        DiscussOptions: {
            /** Efforts */
            efforts: ("low" | "medium" | "high" | "xhigh" | "max")[];
            /**
             * Models
             * @description known model ids for the planner role
             */
            models: string[];
            /** Configured Provider */
            configured_provider: string;
            /** Configured Model */
            configured_model: string | null;
            /** Configured Effort */
            configured_effort: ("low" | "medium" | "high" | "xhigh" | "max") | null;
            /** Configured Session Reuse */
            configured_session_reuse: boolean;
            /** Max Pin Bytes */
            max_pin_bytes: number;
            /** Idle Ttl S */
            idle_ttl_s: number;
        };
        /** DiscussReplyRequest */
        DiscussReplyRequest: {
            /**
             * Text
             * @description an answer, or y / edit / abort at the preview
             */
            text: string;
        };
        /**
         * DiscussSessionModel
         * @description A session, whole. Every field is always present — see `DiscussFrame.data`
         *     for why none of these are defaulted.
         */
        DiscussSessionModel: {
            /** Session Id */
            session_id: string;
            /** Project */
            project: string;
            /**
             * Request
             * @description the operator's opening message
             */
            request: string;
            /**
             * Status
             * @enum {string}
             */
            status: "running" | "awaiting" | "done" | "aborted" | "failed";
            /**
             * Expects
             * @description set only while status is `awaiting`; null otherwise
             */
            expects: ("answer" | "decision" | "retry" | "frozen") | null;
            /** Started At */
            started_at: number;
            /** Last Activity At */
            last_activity_at: number;
            /**
             * Error
             * @description null unless the session failed
             */
            error: string | null;
            /**
             * Applied
             * @description specs written to the store, once approved; empty before that
             */
            applied: {
                [key: string]: unknown;
            }[];
            settings: components["schemas"]["DiscussSettingsModel"];
            /** Pins */
            pins: components["schemas"]["PinnedFileInfo"][];
            /**
             * Frames
             * @description the conversation so far — from `?since=` when one was given, otherwise all of it, for a cold load or a reconnect
             */
            frames: components["schemas"]["DiscussFrame"][];
        };
        /**
         * DiscussSettingsModel
         * @description Session settings. Every field maps to a `plan_or_ask` argument or a config
         *     value the planner call reads — none of them is a preference merely stored.
         *
         *     All of them can be changed mid-session; the loop re-reads them at the top of
         *     each turn, so a change lands on the next planner call, not the next session.
         */
        DiscussSettingsModel: {
            /**
             * Note
             * @description folded into every turn as the HUMAN NOTE block
             * @default
             */
            note: string;
            /**
             * Only Ids
             * @description restrict the backlog excerpt the planner is shown (`plan_or_ask(only_ids=)`); null = the whole backlog
             */
            only_ids?: string[] | null;
            /**
             * Effort
             * @description overrides roles.planner.effort for this session. Higher effort spends more subscription tokens per call
             */
            effort?: ("low" | "medium" | "high" | "xhigh" | "max") | null;
            /**
             * Model
             * @description overrides roles.planner.model for this session
             */
            model?: string | null;
            /**
             * Session Reuse
             * @description overrides run.session_reuse. On, turn 2+ sends only the newest human turn and the provider session supplies the rest — far cheaper, and lost if the session drops
             */
            session_reuse?: boolean | null;
            /**
             * Max Question Rounds
             * @description force a spec proposal after this many clarify rounds. 0 = no limit. Unanswered questions are reported, not dropped
             * @default 0
             */
            max_question_rounds: number;
        };
        /**
         * DiscussState
         * @description `GET …/discuss` — everything a cold page load needs in one request.
         */
        DiscussState: {
            /** Project */
            project: string;
            session?: components["schemas"]["DiscussSessionModel"] | null;
            /**
             * Transcript
             * @description the persisted transcript of the last session (`store.load_discussion`), for history when nothing is live
             * @default
             */
            transcript: string;
            options: components["schemas"]["DiscussOptions"];
            /**
             * Blocked By Job
             * @description a job is in flight, so a session cannot start — its command, for the message
             */
            blocked_by_job?: string | null;
        };
        /** Event */
        Event: {
            /** Rowid */
            rowid: number;
            /** Ts */
            ts: number;
            /** Run Id */
            run_id?: string | null;
            /** Task Id */
            task_id?: string | null;
            /** Kind */
            kind: string;
            /** Detail */
            detail?: string | null;
        };
        /** Events */
        Events: {
            /** Events */
            events: components["schemas"]["Event"][];
            /**
             * Order
             * @description asc = oldest-first (page forward from a cursor); desc = newest-first (the dashboard's recent-events tail)
             * @enum {string}
             */
            order: "asc" | "desc";
            /**
             * Next Since Rowid
             * @description pass back as ?since_rowid= to continue; unchanged when the page was empty. Always the HIGHEST rowid in the page, both orders
             */
            next_since_rowid: number;
            /**
             * Max Rowid
             * @description newest row in the table, for lag display
             */
            max_rowid: number;
        };
        /** GateOutcome */
        GateOutcome: {
            /** Cand Id */
            cand_id: string;
            /** First Attempt */
            first_attempt: boolean;
            /** Passed */
            passed: number;
            /** Failed */
            failed: number;
            /** Pass Rate */
            pass_rate: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Health */
        Health: {
            /**
             * Status
             * @constant
             */
            status: "ok";
            /** Version */
            version: string;
        };
        /**
         * ImportBacklogRequest
         * @description `import-backlog`. Registers stubs from markdown — no LLM, no confirmation.
         *
         *     An empty body is the whole point: this is the one job that costs nothing, so
         *     the UI can offer it as a plain button.
         */
        ImportBacklogRequest: Record<string, never>;
        /** Job */
        Job: {
            /** Job Id */
            job_id: string;
            /** Project */
            project: string;
            /**
             * Command
             * @enum {string}
             */
            command: "run" | "plan" | "resume" | "import-backlog" | "reconcile";
            /**
             * Status
             * @enum {string}
             */
            status: "starting" | "running" | "exited" | "stopped" | "failed";
            /** Argv */
            argv: string[];
            /** Pid */
            pid?: number | null;
            /** Run Id */
            run_id?: string | null;
            /** Started At */
            started_at: number;
            /** Ended At */
            ended_at?: number | null;
            /** Exit Code */
            exit_code?: number | null;
            /** Log Path */
            log_path?: string | null;
        };
        /**
         * JobAccepted
         * @description 202 body for every spawn. `run_id` is null until the child mints it.
         */
        JobAccepted: {
            /** Job Id */
            job_id: string;
            /** Project */
            project: string;
            /**
             * Command
             * @enum {string}
             */
            command: "run" | "plan" | "resume" | "import-backlog" | "reconcile";
            /**
             * Argv
             * @description the exact command line spawned — the panel shows it so a human can reproduce the job in a terminal
             */
            argv: string[];
            /** Run Id */
            run_id?: string | null;
        };
        /** JobLog */
        JobLog: {
            /** Job Id */
            job_id: string;
            /**
             * Offset
             * @description byte offset this chunk starts at
             */
            offset: number;
            /** Next Offset */
            next_offset: number;
            /** Eof */
            eof: boolean;
            /** Text */
            text: string;
        };
        /** Jobs */
        Jobs: {
            /** Jobs */
            jobs: components["schemas"]["Job"][];
        };
        /** Metrics */
        Metrics: {
            /** Completed Tasks */
            completed_tasks: number;
            /** Gate Outcomes */
            gate_outcomes: components["schemas"]["GateOutcome"][];
            /**
             * Event Counts
             * @description the kinds `orchestrator metrics` counts; 0-filled
             */
            event_counts: {
                [key: string]: number;
            };
            /** Subscription Tokens By Role */
            subscription_tokens_by_role: components["schemas"]["RoleTokens"][];
            /** Subscription In Tok Per Completed Task */
            subscription_in_tok_per_completed_task?: number | null;
            /** Cash Usd Per Completed Task */
            cash_usd_per_completed_task?: number | null;
            /** Queue Stats */
            queue_stats: {
                [key: string]: number;
            };
        };
        /**
         * PinRequest
         * @description Names an existing pin, for removal. Not a location — see `PinnedFileInfo`.
         */
        PinRequest: {
            /**
             * Path
             * @description the pin's display path, as `PinnedFileInfo.path`
             */
            path: string;
        };
        /**
         * PinnedFileInfo
         * @description A file attached to every planner turn. The text is not echoed back — the
         *     UI already has it, and a 64KB blob per pin in every poll response is waste.
         */
        PinnedFileInfo: {
            /**
             * Path
             * @description a display name under `uploaded/`, not a location. The content was sent by the operator and exists nowhere on disk
             */
            path: string;
            /** Bytes */
            bytes: number;
            /**
             * Truncated
             * @description the file exceeded the pin cap and only its head is in the prompt
             */
            truncated: boolean;
        };
        /**
         * PlanRequest
         * @description `plan`. Spends planner tokens, so it is confirm-gated too.
         */
        PlanRequest: {
            /**
             * Confirm
             * @description required — planning spends tokens
             * @default false
             */
            confirm: boolean;
            /** Tasks */
            tasks?: string[] | null;
            /**
             * All Needs Plan
             * @description `--all-needs-plan`: plan every needs_plan task
             * @default false
             */
            all_needs_plan: boolean;
            /** Limit */
            limit?: number | null;
            /**
             * Note
             * @description free-text steer, passed as the positional argument
             * @default
             */
            note: string;
        };
        /** Project */
        Project: {
            /** Name */
            name: string;
            /**
             * Profile Path
             * @description profile that defines it, when it came from disk
             */
            profile_path?: string | null;
            /** Has Store */
            has_store: boolean;
            /** Store Path */
            store_path: string | null;
            /** Has Checkpoints */
            has_checkpoints: boolean;
            /**
             * Repo Path
             * @description the EFFECTIVE value after the config merge; null when it is set nowhere — such a project is readable but cannot run jobs
             */
            repo_path?: string | null;
            /**
             * Repo Path Source
             * @description which layer supplied repo_path: this project's own 'profile', the machine-global config/local.yaml ('global'), or 'env'. null when unset
             */
            repo_path_source?: ("profile" | "global" | "env") | null;
            /**
             * Runnable
             * @description a checkout resolves, so job endpoints that need one will not 409. Read together with repo_path_source: 'global' means the checkout is not this project's own
             */
            runnable: boolean;
            /**
             * Runnable Detail
             * @description why it cannot run, or the caveat when repo_path was inherited rather than declared; null when the project's own profile names its checkout
             */
            runnable_detail?: string | null;
            /**
             * Is Active
             * @description matches ORCH_PROJECT
             */
            is_active: boolean;
        };
        /** Projects */
        Projects: {
            /** Projects */
            projects: components["schemas"]["Project"][];
            /**
             * Active
             * @description ORCH_PROJECT, if set and allowlisted
             */
            active?: string | null;
        };
        /**
         * ReconcileRequest
         * @description `reconcile`. Rewrites abandoned `running` rows to `aborted` — no LLM, no
         *     git, so no confirmation. The only mutation in the panel that costs nothing.
         */
        ReconcileRequest: {
            /**
             * Dry Run
             * @description list what would be closed and change nothing
             * @default false
             */
            dry_run: boolean;
        };
        /**
         * ResumeRequest
         * @description `resume`. Continues the paused run, so it spends whatever remains.
         */
        ResumeRequest: {
            /**
             * Confirm
             * @description required — resuming continues spending
             * @default false
             */
            confirm: boolean;
        };
        /** RoleTokens */
        RoleTokens: {
            /** Role */
            role: string;
            /** Calls */
            calls: number;
            /** In Tok */
            in_tok: number;
            /** Out Tok */
            out_tok: number;
            /** Cache Hit */
            cache_hit: number;
            /** In Tok Per Completed Task */
            in_tok_per_completed_task?: number | null;
        };
        /** RunDetail */
        RunDetail: {
            /** Id */
            id: string;
            /** Started At */
            started_at: number;
            /** Status */
            status: ("running" | "paused" | "done" | "aborted") | string;
            /** Note */
            note?: string | null;
            /**
             * Cost Usd
             * @default 0
             */
            cost_usd: number;
            tokens: components["schemas"]["TokenChannels"];
            /**
             * Last Activity At
             * @description newest events/usage row this run wrote; null when it wrote none. Not the same as started_at
             */
            last_activity_at?: number | null;
            /**
             * Stale
             * @description the row says `running` but nothing has happened for `stale_after_s` — the process died without writing a terminal status. Render it as stalled, not running; `reconcile` closes it
             * @default false
             */
            stale: boolean;
            /**
             * Stale After S
             * @description the silence the `stale` flag was computed against
             * @default 900
             */
            stale_after_s: number;
            /** Task Ids */
            task_ids: string[];
            /** Events */
            events: components["schemas"]["Event"][];
        };
        /** RunListItem */
        RunListItem: {
            /** Id */
            id: string;
            /** Started At */
            started_at: number;
            /** Status */
            status: ("running" | "paused" | "done" | "aborted") | string;
            /** Note */
            note?: string | null;
            /**
             * Cost Usd
             * @default 0
             */
            cost_usd: number;
            tokens: components["schemas"]["TokenChannels"];
            /**
             * Last Activity At
             * @description newest events/usage row this run wrote; null when it wrote none. Not the same as started_at
             */
            last_activity_at?: number | null;
            /**
             * Stale
             * @description the row says `running` but nothing has happened for `stale_after_s` — the process died without writing a terminal status. Render it as stalled, not running; `reconcile` closes it
             * @default false
             */
            stale: boolean;
            /**
             * Stale After S
             * @description the silence the `stale` flag was computed against
             * @default 900
             */
            stale_after_s: number;
        };
        /**
         * RunRequest
         * @description `run`. The only endpoint in the API that can spend subscription quota.
         */
        RunRequest: {
            /**
             * Confirm
             * @description required for a real run — it spends quota and writes to git worktrees. Not required when dry_run is true
             * @default false
             */
            confirm: boolean;
            /**
             * Dry Run
             * @description `--dry-run`: the runner prints the schedule and exits. Zero tokens, zero git, so no confirmation is asked for
             * @default false
             */
            dry_run: boolean;
            /**
             * Tasks
             * @description explicit task ids; null lets the scheduler pick
             */
            tasks?: string[] | null;
            /**
             * N
             * @description `--n`: override `n_candidates` (best-of-N) for EVERY task this run dispatches, replacing each task's planner-set count. This is a multiplier on LLM calls, not a cap on anything — there is no cap-on-tasks flag. Null leaves each task's own spec alone
             */
            n?: number | null;
        };
        /** Runs */
        Runs: {
            /** Runs */
            runs: components["schemas"]["RunListItem"][];
        };
        /**
         * StartDiscussRequest
         * @description Opening a session spends planner tokens on its very first turn, so it is
         *     confirm-gated exactly like `plan`.
         */
        StartDiscussRequest: {
            /**
             * Request
             * @description the opening message / feature description
             */
            request: string;
            /**
             * Confirm
             * @description required — the planner call spends quota
             * @default false
             */
            confirm: boolean;
            settings?: components["schemas"]["DiscussSettingsModel"];
            /**
             * Uploads
             * @description files sent from the operator's machine, attached from the first turn. Here rather than in a follow-up request because the first turn is the expensive one and is started by this call
             */
            uploads?: components["schemas"]["UploadedPin"][];
        };
        /**
         * StreamCursor
         * @description `event: tasks|runs|usage|jobs` — a signal, not data. Refetch the entity.
         *
         *     The cursor is an opaque digest: compare it for equality, never parse it.
         */
        StreamCursor: {
            /** Cursor */
            cursor: string;
        };
        /**
         * StreamEvents
         * @description `event: events` — the one frame carrying rows, because the log is append-only.
         */
        StreamEvents: {
            /** Events */
            events: components["schemas"]["Event"][];
            /** Next Since Rowid */
            next_since_rowid: number;
            /**
             * Truncated
             * @description the burst hit the server's per-frame cap; refetch from next_since_rowid rather than trusting this frame to be complete
             */
            truncated: boolean;
        };
        /**
         * StreamFrame
         * @description Documentation-only envelope: which payload arrives with which event name.
         *
         *     SSE carries the name in the frame's `event:` line, not inside `data`, so this
         *     cannot be a discriminated union — the client switches on the event name and
         *     then reads `data` as the matching member.
         */
        StreamFrame: {
            /** Data */
            data: components["schemas"]["StreamHello"] | components["schemas"]["StreamEvents"] | components["schemas"]["StreamHeartbeat"] | components["schemas"]["StreamCursor"];
        };
        /**
         * StreamHeartbeat
         * @description `event: heartbeat` — only sent when a tick produced nothing else.
         */
        StreamHeartbeat: {
            /** Event Rowid */
            event_rowid: number;
        };
        /**
         * StreamHello
         * @description `event: hello` — the first frame, and the thing that makes reconnects cheap.
         *
         *     A client adopts `event_rowid`, refetches once, and receives only deltas after
         *     that; without it a reconnect either replays the log or silently drops the
         *     rows written while it was away.
         */
        StreamHello: {
            /** Tasks */
            tasks: string;
            /** Runs */
            runs: string;
            /** Usage */
            usage: string;
            /** Events */
            events: string;
            /** Jobs */
            jobs: string;
            /**
             * Event Rowid
             * @description the client is caught up to this rowid
             */
            event_rowid: number;
            /**
             * Poll Interval S
             * @description server's tick, for staleness UI
             */
            poll_interval_s: number;
        };
        /** Summary */
        Summary: {
            /** Project */
            project: string;
            /** Task Count */
            task_count: number;
            /** Queue Stats */
            queue_stats: {
                [key: string]: number;
            };
            /** Domain Stats */
            domain_stats: {
                [key: string]: number;
            };
            /** @description the running/paused run, if any */
            active_run?: components["schemas"]["RunListItem"] | null;
            last_run?: components["schemas"]["RunListItem"] | null;
            totals: components["schemas"]["TokenChannels"];
            /** Cash Spend Usd */
            cash_spend_usd: number;
            /** Event Counts */
            event_counts: {
                [key: string]: number;
            };
            /** Max Event Rowid */
            max_event_rowid: number;
        };
        /** TaskDetail */
        TaskDetail: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Status */
            status: ("ready" | "running" | "needs_human" | "done" | "failed" | "rejected" | "human_only" | "needs_plan") | string;
            /** Milestone */
            milestone?: string | null;
            /**
             * Retries
             * @default 0
             */
            retries: number;
            /**
             * Cost Usd
             * @default 0
             */
            cost_usd: number;
            /** Updated At */
            updated_at?: number | null;
            /** Domain */
            domain?: string | null;
            /** Risk */
            risk?: string | null;
            /** Complexity */
            complexity?: string | null;
            /** Visual */
            visual?: boolean | null;
            /** Agent Able */
            agent_able?: boolean | null;
            /** N Candidates */
            n_candidates?: number | null;
            /** Parent Id */
            parent_id?: string | null;
            /** Deps */
            deps?: string[];
            /** Files Read */
            files_read?: string[];
            /** Files Write */
            files_write?: string[];
            /** Acceptance */
            acceptance?: string[];
            /**
             * Cash Spend Usd
             * @description lifetime cash across runs; tasks.cost_usd is the same figure accumulated at write time and can lag a re-run
             */
            cash_spend_usd: number;
            /**
             * Children
             * @description sub-task ids when this task was decomposed
             */
            children?: string[];
            /**
             * Spec
             * @description raw planner spec blob, unfiltered
             */
            spec: {
                [key: string]: unknown;
            };
            /** Events */
            events?: components["schemas"]["Event"][];
        };
        /** TaskListItem */
        TaskListItem: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Status */
            status: ("ready" | "running" | "needs_human" | "done" | "failed" | "rejected" | "human_only" | "needs_plan") | string;
            /** Milestone */
            milestone?: string | null;
            /**
             * Retries
             * @default 0
             */
            retries: number;
            /**
             * Cost Usd
             * @default 0
             */
            cost_usd: number;
            /** Updated At */
            updated_at?: number | null;
            /** Domain */
            domain?: string | null;
            /** Risk */
            risk?: string | null;
            /** Complexity */
            complexity?: string | null;
            /** Visual */
            visual?: boolean | null;
            /** Agent Able */
            agent_able?: boolean | null;
            /** N Candidates */
            n_candidates?: number | null;
            /** Parent Id */
            parent_id?: string | null;
            /** Deps */
            deps?: string[];
        };
        /** Tasks */
        Tasks: {
            /** Tasks */
            tasks: components["schemas"]["TaskListItem"][];
            /**
             * Total
             * @description rows matching the filter
             */
            total: number;
            /**
             * Queue Stats
             * @description status -> count for the FILTERED set
             */
            queue_stats: {
                [key: string]: number;
            };
        };
        /**
         * TokenChannels
         * @description Both billing channels, either of which may be absent (no calls yet).
         */
        TokenChannels: {
            cash?: components["schemas"]["ChannelTotals"] | null;
            subscription?: components["schemas"]["ChannelTotals"] | null;
        };
        /**
         * UploadedPin
         * @description File content sent from the operator's machine — a log, a spec, notes out
         *     of a tracker, or a source file they would rather point at than describe.
         *
         *     Content, never a path into the checkout. Naming a path was the earlier
         *     design and is gone: it asked the operator to hand-type something the planner
         *     can usually find on its own, and it could not carry the case that matters
         *     most, a file that is not in the repo at all.
         *
         *     Text in JSON, not a multipart body: the request that most needs an upload is
         *     `POST …/discuss`, which creates the session *and* starts the billable first
         *     turn, so a pin that arrives in a second request has already missed the turn
         *     it was for. Uploading through the same JSON keeps the staged case and the
         *     live case on one mechanism.
         *
         *     The planner prompt is text; an image cannot reach it in any form, so a binary
         *     upload is refused with that reason rather than pinned as unreadable filler.
         */
        UploadedPin: {
            /**
             * Name
             * @description the original filename, reduced server-side to a safe display name under `uploaded/`
             */
            name: string;
            /**
             * Text
             * @description the file's text. Over the per-pin cap it is truncated and reported as such
             */
            text: string;
        };
        /** Usage */
        Usage: {
            /**
             * Group By
             * @enum {string}
             */
            group_by: "role" | "model" | "provider" | "day";
            /** Rows */
            rows: components["schemas"]["UsageRow"][];
            totals: components["schemas"]["TokenChannels"];
        };
        /** UsageRow */
        UsageRow: {
            /**
             * Key
             * @description human label for the group
             */
            key: string;
            /**
             * Cash
             * @description False = subscription tier (logged, not billed)
             */
            cash: boolean;
            /** Role */
            role?: string | null;
            /** Provider */
            provider?: string | null;
            /** Model */
            model?: string | null;
            /**
             * Day
             * @description local YYYY-MM-DD, when group_by=day
             */
            day?: string | null;
            /** Calls */
            calls: number;
            /** In Tok */
            in_tok: number;
            /** Out Tok */
            out_tok: number;
            /** Cache Hit */
            cache_hit: number;
            /** Cache Miss */
            cache_miss: number;
            /** Cost */
            cost: number;
            /**
             * Cache Hit Rate
             * @description hit/(hit+miss); null when the provider reported no cache telemetry at all — never 0.0 for 'unknown'
             */
            cache_hit_rate?: number | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** Wave */
        Wave: {
            /**
             * Index
             * @description 1-based, matches `run --dry-run` output
             */
            index: number;
            /** Tasks */
            tasks: components["schemas"]["WaveTask"][];
        };
        /** WaveTask */
        WaveTask: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Domain */
            domain?: string | null;
            /** N Candidates */
            n_candidates: number;
            /**
             * Candidates
             * @description worker_models keys that would run
             */
            candidates: string[];
            /** Files Write */
            files_write?: string[];
            /** Files Read */
            files_read?: string[];
        };
        /** Waves */
        Waves: {
            /** Max Parallel Tasks */
            max_parallel_tasks: number;
            /** Default N Candidates */
            default_n_candidates: number;
            /** Waves */
            waves: components["schemas"]["Wave"][];
            /**
             * Unreachable
             * @description ready tasks no wave can reach this run (unmet deps)
             */
            unreachable?: string[];
            /**
             * Seam Missing Deps
             * @description seam-domain tasks with no deps — almost always a planner mistake
             */
            seam_missing_deps?: string[];
            /** Queue Stats */
            queue_stats: {
                [key: string]: number;
            };
            /** Domain Stats */
            domain_stats: {
                [key: string]: number;
            };
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    list_projects: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Projects"];
                };
            };
        };
    };
    summary: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Summary"];
                };
            };
            /** @description project is not in the allowlist */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description the project is real but has no state/<project>.sqlite3 yet */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    waves: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Waves"];
                };
            };
            /** @description project is not in the allowlist */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description the project is real but has no state/<project>.sqlite3 yet */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_tasks: {
        parameters: {
            query?: {
                status?: string | null;
                milestone?: string | null;
                domain?: string | null;
                parent_id?: string | null;
                /** @description substring of id or title */
                q?: string | null;
            };
            header?: never;
            path: {
                project: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Tasks"];
                };
            };
            /** @description project is not in the allowlist */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description the project is real but has no state/<project>.sqlite3 yet */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_task: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
                project: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskDetail"];
                };
            };
            /** @description unknown project, or no such row in this project */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description the project is real but has no state/<project>.sqlite3 yet */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_candidates: {
        parameters: {
            query?: {
                run_id?: string | null;
            };
            header?: never;
            path: {
                task_id: string;
                project: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Candidates"];
                };
            };
            /** @description unknown project, or no such row in this project */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description the project is real but has no state/<project>.sqlite3 yet */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_runs: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                project: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Runs"];
                };
            };
            /** @description project is not in the allowlist */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description the project is real but has no state/<project>.sqlite3 yet */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run: {
        parameters: {
            query?: {
                event_limit?: number;
            };
            header?: never;
            path: {
                run_id: string;
                project: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunDetail"];
                };
            };
            /** @description unknown project, or no such row in this project */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description the project is real but has no state/<project>.sqlite3 yet */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    usage: {
        parameters: {
            query?: {
                group_by?: "role" | "model" | "provider" | "day";
            };
            header?: never;
            path: {
                project: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Usage"];
                };
            };
            /** @description project is not in the allowlist */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description the project is real but has no state/<project>.sqlite3 yet */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    metrics: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Metrics"];
                };
            };
            /** @description project is not in the allowlist */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description the project is real but has no state/<project>.sqlite3 yet */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_events: {
        parameters: {
            query?: {
                since_rowid?: number | null;
                kind?: string | null;
                task_id?: string | null;
                run_id?: string | null;
                limit?: number;
                /** @description asc pages forward from since_rowid; desc returns the newest matching rows */
                order?: "asc" | "desc";
            };
            header?: never;
            path: {
                project: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Events"];
                };
            };
            /** @description project is not in the allowlist */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description the project is real but has no state/<project>.sqlite3 yet */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_jobs: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Jobs"];
                };
            };
            /** @description project is not in the allowlist */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
                project: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            /** @description unknown project, or unknown job id */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_log: {
        parameters: {
            query?: {
                offset?: number;
                max_bytes?: number;
            };
            header?: never;
            path: {
                job_id: string;
                project: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobLog"];
                };
            };
            /** @description unknown project, or unknown job id */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_run: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobAccepted"];
                };
            };
            /** @description unknown project (and, for resume, no paused run to continue) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description a job is already in flight for this project, the profile has no project.repo_path, or the store does not exist yet */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_plan: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlanRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobAccepted"];
                };
            };
            /** @description unknown project (and, for resume, no paused run to continue) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description a job is already in flight for this project, the profile has no project.repo_path, or the store does not exist yet */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_resume: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResumeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobAccepted"];
                };
            };
            /** @description unknown project (and, for resume, no paused run to continue) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description a job is already in flight for this project, the profile has no project.repo_path, or the store does not exist yet */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_import_backlog: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ImportBacklogRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobAccepted"];
                };
            };
            /** @description unknown project (and, for resume, no paused run to continue) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description a job is already in flight for this project, the profile has no project.repo_path, or the store does not exist yet */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_reconcile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ReconcileRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobAccepted"];
                };
            };
            /** @description unknown project (and, for resume, no paused run to continue) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description a job is already in flight for this project, the profile has no project.repo_path, or the store does not exist yet */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stop_job: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
                project: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            /** @description unknown project, or unknown job id */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_discuss: {
        parameters: {
            query?: {
                /** @description replay cursor: return only frames newer than this seq */
                since?: number;
            };
            header?: never;
            path: {
                project: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiscussState"];
                };
            };
            /** @description unknown project, or unknown discuss session */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description a discuss session is already open for this project, or the profile has no project.repo_path */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_discuss: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StartDiscussRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiscussSessionModel"];
                };
            };
            /** @description unknown project, or unknown discuss session */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description a discuss session is already open for this project, or the profile has no project.repo_path */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    close_discuss: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
                project: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiscussSessionModel"];
                };
            };
            /** @description unknown project, or unknown discuss session */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description a discuss session is already open for this project, or the profile has no project.repo_path */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reply: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
                project: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DiscussReplyRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiscussSessionModel"];
                };
            };
            /** @description unknown project, or unknown discuss session */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description a discuss session is already open for this project, or the profile has no project.repo_path */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_discuss: {
        parameters: {
            query?: {
                since?: number;
            };
            header?: never;
            path: {
                session_id: string;
                project: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description SSE. Each `message` frame is one DiscussFrame. Reconnect with ?since=<seq> to replay from a cursor rather than lose the conversation. The stream ends after the `closed` frame. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiscussFrame"];
                    "text/event-stream": unknown;
                };
            };
            /** @description unknown project, or unknown discuss session */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description a discuss session is already open for this project, or the profile has no project.repo_path */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_settings: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
                project: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DiscussSettingsModel"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiscussSessionModel"];
                };
            };
            /** @description unknown project, or unknown discuss session */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description a discuss session is already open for this project, or the profile has no project.repo_path */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_pin: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
                project: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UploadedPin"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiscussSessionModel"];
                };
            };
            /** @description unknown project, or unknown discuss session */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description a discuss session is already open for this project, or the profile has no project.repo_path */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_pin: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
                project: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PinRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiscussSessionModel"];
                };
            };
            /** @description unknown project, or unknown discuss session */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description a discuss session is already open for this project, or the profile has no project.repo_path */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description SSE. Named events: hello, tasks, runs, usage, events, jobs, heartbeat. Every one but `events` carries only a cursor — refetch the entity through its normal GET. The declared model is one frame's `data`; the frame name arrives in the SSE `event:` line. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StreamFrame"];
                    "text/event-stream": unknown;
                };
            };
            /** @description project is not in the allowlist */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
