/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Healthz */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Projects */
        get: operations["list_projects_api_projects_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project}/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Summary */
        get: operations["summary_api_projects__project__summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project}/waves": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Waves */
        get: operations["waves_api_projects__project__waves_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project}/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Tasks */
        get: operations["list_tasks_api_projects__project__tasks_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project}/tasks/{task_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Task */
        get: operations["get_task_api_projects__project__tasks__task_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project}/tasks/{task_id}/candidates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Candidates
         * @description Per-candidate detail: the checkpoint when there is one, else the event log.
         *
         *     The checkpoint is authoritative and live (it holds the attempt currently
         *     running); the events fallback is history for a task whose checkpoint was
         *     pruned or which ran before the panel existed. `source` tells the UI which it
         *     got, because only the checkpoint can show an in-flight attempt.
         */
        get: operations["get_candidates_api_projects__project__tasks__task_id__candidates_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project}/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Runs */
        get: operations["list_runs_api_projects__project__runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project}/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run */
        get: operations["get_run_api_projects__project__runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project}/usage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Usage */
        get: operations["usage_api_projects__project__usage_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project}/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Metrics */
        get: operations["metrics_api_projects__project__metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Events */
        get: operations["list_events_api_projects__project__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project}/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Jobs */
        get: operations["list_jobs_api_projects__project__jobs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project}/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job */
        get: operations["get_job_api_projects__project__jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project}/jobs/{job_id}/log": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job Log */
        get: operations["get_job_log_api_projects__project__jobs__job_id__log_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Candidate */
        Candidate: {
            /** Cand Id */
            cand_id: string;
            /** Attempt */
            attempt: number;
            /**
             * Status
             * @description gate_passed | gate_failed | patch_failed | llm_failed | visual_failed | visual_unverifiable | skipped
             */
            status?: string | null;
            /** Model */
            model?: string | null;
            /** Branch */
            branch?: string | null;
            /** Worktree */
            worktree?: string | null;
            /**
             * No Patch
             * @default false
             */
            no_patch: boolean;
            /** Error */
            error?: string | null;
            /**
             * Gate Log
             * @description tail only, never the full log
             */
            gate_log?: string | null;
            /** Notes */
            notes?: string | null;
            /**
             * Has Diff
             * @default false
             */
            has_diff: boolean;
            /** Visual Facts */
            visual_facts?: {
                [key: string]: unknown;
            } | null;
        };
        /** Candidates */
        Candidates: {
            /** Task Id */
            task_id: string;
            /**
             * Run Id
             * @description run whose thread was read
             */
            run_id?: string | null;
            /**
             * Source
             * @enum {string}
             */
            source: "checkpoint" | "events" | "none";
            /** Candidates */
            candidates: components["schemas"]["Candidate"][];
        };
        /** ChannelTotals */
        ChannelTotals: {
            /** Calls */
            calls: number;
            /** In Tok */
            in_tok: number;
            /** Out Tok */
            out_tok: number;
            /** Cache Hit */
            cache_hit: number;
            /** Cache Miss */
            cache_miss: number;
            /**
             * Cost
             * @description USD; real for cash, notional quota for subscription
             */
            cost: number;
        };
        /** Event */
        Event: {
            /** Rowid */
            rowid: number;
            /** Ts */
            ts: number;
            /** Run Id */
            run_id?: string | null;
            /** Task Id */
            task_id?: string | null;
            /** Kind */
            kind: string;
            /** Detail */
            detail?: string | null;
        };
        /** Events */
        Events: {
            /** Events */
            events: components["schemas"]["Event"][];
            /**
             * Next Since Rowid
             * @description pass back as ?since_rowid= to continue; unchanged when the page was empty
             */
            next_since_rowid: number;
            /**
             * Max Rowid
             * @description newest row in the table, for lag display
             */
            max_rowid: number;
        };
        /** GateOutcome */
        GateOutcome: {
            /** Cand Id */
            cand_id: string;
            /** First Attempt */
            first_attempt: boolean;
            /** Passed */
            passed: number;
            /** Failed */
            failed: number;
            /** Pass Rate */
            pass_rate: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Health */
        Health: {
            /**
             * Status
             * @constant
             */
            status: "ok";
            /** Version */
            version: string;
        };
        /** Job */
        Job: {
            /** Job Id */
            job_id: string;
            /** Project */
            project: string;
            /**
             * Command
             * @enum {string}
             */
            command: "run" | "plan" | "resume" | "import-backlog";
            /**
             * Status
             * @enum {string}
             */
            status: "starting" | "running" | "exited" | "stopped" | "failed";
            /** Argv */
            argv: string[];
            /** Pid */
            pid?: number | null;
            /** Run Id */
            run_id?: string | null;
            /** Started At */
            started_at: number;
            /** Ended At */
            ended_at?: number | null;
            /** Exit Code */
            exit_code?: number | null;
            /** Log Path */
            log_path?: string | null;
        };
        /** JobLog */
        JobLog: {
            /** Job Id */
            job_id: string;
            /**
             * Offset
             * @description byte offset this chunk starts at
             */
            offset: number;
            /** Next Offset */
            next_offset: number;
            /** Eof */
            eof: boolean;
            /** Text */
            text: string;
        };
        /** Jobs */
        Jobs: {
            /** Jobs */
            jobs: components["schemas"]["Job"][];
        };
        /** Metrics */
        Metrics: {
            /** Completed Tasks */
            completed_tasks: number;
            /** Gate Outcomes */
            gate_outcomes: components["schemas"]["GateOutcome"][];
            /**
             * Event Counts
             * @description the kinds `orchestrator metrics` counts; 0-filled
             */
            event_counts: {
                [key: string]: number;
            };
            /** Subscription Tokens By Role */
            subscription_tokens_by_role: components["schemas"]["RoleTokens"][];
            /** Subscription In Tok Per Completed Task */
            subscription_in_tok_per_completed_task?: number | null;
            /** Cash Usd Per Completed Task */
            cash_usd_per_completed_task?: number | null;
            /** Queue Stats */
            queue_stats: {
                [key: string]: number;
            };
        };
        /** Project */
        Project: {
            /** Name */
            name: string;
            /**
             * Profile Path
             * @description profile that defines it, when it came from disk
             */
            profile_path?: string | null;
            /** Has Store */
            has_store: boolean;
            /** Store Path */
            store_path: string | null;
            /** Has Checkpoints */
            has_checkpoints: boolean;
            /**
             * Repo Path
             * @description null when the profile has no project.repo_path — such a project is readable but cannot run jobs
             */
            repo_path?: string | null;
            /**
             * Is Active
             * @description matches ORCH_PROJECT
             */
            is_active: boolean;
        };
        /** Projects */
        Projects: {
            /** Projects */
            projects: components["schemas"]["Project"][];
            /**
             * Active
             * @description ORCH_PROJECT, if set and allowlisted
             */
            active?: string | null;
        };
        /** RoleTokens */
        RoleTokens: {
            /** Role */
            role: string;
            /** Calls */
            calls: number;
            /** In Tok */
            in_tok: number;
            /** Out Tok */
            out_tok: number;
            /** Cache Hit */
            cache_hit: number;
            /** In Tok Per Completed Task */
            in_tok_per_completed_task?: number | null;
        };
        /** RunDetail */
        RunDetail: {
            /** Id */
            id: string;
            /** Started At */
            started_at: number;
            /** Status */
            status: ("running" | "paused" | "done" | "aborted") | string;
            /** Note */
            note?: string | null;
            /**
             * Cost Usd
             * @default 0
             */
            cost_usd: number;
            tokens: components["schemas"]["TokenChannels"];
            /** Task Ids */
            task_ids: string[];
            /** Events */
            events: components["schemas"]["Event"][];
        };
        /** RunListItem */
        RunListItem: {
            /** Id */
            id: string;
            /** Started At */
            started_at: number;
            /** Status */
            status: ("running" | "paused" | "done" | "aborted") | string;
            /** Note */
            note?: string | null;
            /**
             * Cost Usd
             * @default 0
             */
            cost_usd: number;
            tokens: components["schemas"]["TokenChannels"];
        };
        /** Runs */
        Runs: {
            /** Runs */
            runs: components["schemas"]["RunListItem"][];
        };
        /** Summary */
        Summary: {
            /** Project */
            project: string;
            /** Task Count */
            task_count: number;
            /** Queue Stats */
            queue_stats: {
                [key: string]: number;
            };
            /** Domain Stats */
            domain_stats: {
                [key: string]: number;
            };
            /** @description the running/paused run, if any */
            active_run?: components["schemas"]["RunListItem"] | null;
            last_run?: components["schemas"]["RunListItem"] | null;
            totals: components["schemas"]["TokenChannels"];
            /** Cash Spend Usd */
            cash_spend_usd: number;
            /** Event Counts */
            event_counts: {
                [key: string]: number;
            };
            /** Max Event Rowid */
            max_event_rowid: number;
        };
        /** TaskDetail */
        TaskDetail: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Status */
            status: ("ready" | "running" | "needs_human" | "done" | "failed" | "rejected" | "human_only" | "needs_plan") | string;
            /** Milestone */
            milestone?: string | null;
            /**
             * Retries
             * @default 0
             */
            retries: number;
            /**
             * Cost Usd
             * @default 0
             */
            cost_usd: number;
            /** Updated At */
            updated_at?: number | null;
            /** Domain */
            domain?: string | null;
            /** Risk */
            risk?: string | null;
            /** Complexity */
            complexity?: string | null;
            /** Visual */
            visual?: boolean | null;
            /** Agent Able */
            agent_able?: boolean | null;
            /** N Candidates */
            n_candidates?: number | null;
            /** Parent Id */
            parent_id?: string | null;
            /** Deps */
            deps?: string[];
            /** Files Read */
            files_read?: string[];
            /** Files Write */
            files_write?: string[];
            /** Acceptance */
            acceptance?: string[];
            /**
             * Cash Spend Usd
             * @description lifetime cash across runs; tasks.cost_usd is the same figure accumulated at write time and can lag a re-run
             */
            cash_spend_usd: number;
            /**
             * Children
             * @description sub-task ids when this task was decomposed
             */
            children?: string[];
            /**
             * Spec
             * @description raw planner spec blob, unfiltered
             */
            spec: {
                [key: string]: unknown;
            };
            /** Events */
            events?: components["schemas"]["Event"][];
        };
        /** TaskListItem */
        TaskListItem: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Status */
            status: ("ready" | "running" | "needs_human" | "done" | "failed" | "rejected" | "human_only" | "needs_plan") | string;
            /** Milestone */
            milestone?: string | null;
            /**
             * Retries
             * @default 0
             */
            retries: number;
            /**
             * Cost Usd
             * @default 0
             */
            cost_usd: number;
            /** Updated At */
            updated_at?: number | null;
            /** Domain */
            domain?: string | null;
            /** Risk */
            risk?: string | null;
            /** Complexity */
            complexity?: string | null;
            /** Visual */
            visual?: boolean | null;
            /** Agent Able */
            agent_able?: boolean | null;
            /** N Candidates */
            n_candidates?: number | null;
            /** Parent Id */
            parent_id?: string | null;
            /** Deps */
            deps?: string[];
        };
        /** Tasks */
        Tasks: {
            /** Tasks */
            tasks: components["schemas"]["TaskListItem"][];
            /**
             * Total
             * @description rows matching the filter
             */
            total: number;
            /**
             * Queue Stats
             * @description status -> count for the FILTERED set
             */
            queue_stats: {
                [key: string]: number;
            };
        };
        /**
         * TokenChannels
         * @description Both billing channels, either of which may be absent (no calls yet).
         */
        TokenChannels: {
            cash?: components["schemas"]["ChannelTotals"] | null;
            subscription?: components["schemas"]["ChannelTotals"] | null;
        };
        /** Usage */
        Usage: {
            /**
             * Group By
             * @enum {string}
             */
            group_by: "role" | "model" | "provider" | "day";
            /** Rows */
            rows: components["schemas"]["UsageRow"][];
            totals: components["schemas"]["TokenChannels"];
        };
        /** UsageRow */
        UsageRow: {
            /**
             * Key
             * @description human label for the group
             */
            key: string;
            /**
             * Cash
             * @description False = subscription tier (logged, not billed)
             */
            cash: boolean;
            /** Role */
            role?: string | null;
            /** Provider */
            provider?: string | null;
            /** Model */
            model?: string | null;
            /**
             * Day
             * @description local YYYY-MM-DD, when group_by=day
             */
            day?: string | null;
            /** Calls */
            calls: number;
            /** In Tok */
            in_tok: number;
            /** Out Tok */
            out_tok: number;
            /** Cache Hit */
            cache_hit: number;
            /** Cache Miss */
            cache_miss: number;
            /** Cost */
            cost: number;
            /**
             * Cache Hit Rate
             * @description hit/(hit+miss); null when the provider reported no cache telemetry at all — never 0.0 for 'unknown'
             */
            cache_hit_rate?: number | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** Wave */
        Wave: {
            /**
             * Index
             * @description 1-based, matches `run --dry-run` output
             */
            index: number;
            /** Tasks */
            tasks: components["schemas"]["WaveTask"][];
        };
        /** WaveTask */
        WaveTask: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Domain */
            domain?: string | null;
            /** N Candidates */
            n_candidates: number;
            /**
             * Candidates
             * @description worker_models keys that would run
             */
            candidates: string[];
            /** Files Write */
            files_write?: string[];
            /** Files Read */
            files_read?: string[];
        };
        /** Waves */
        Waves: {
            /** Max Parallel Tasks */
            max_parallel_tasks: number;
            /** Default N Candidates */
            default_n_candidates: number;
            /** Waves */
            waves: components["schemas"]["Wave"][];
            /**
             * Unreachable
             * @description ready tasks no wave can reach this run (unmet deps)
             */
            unreachable?: string[];
            /**
             * Seam Missing Deps
             * @description seam-domain tasks with no deps — almost always a planner mistake
             */
            seam_missing_deps?: string[];
            /** Queue Stats */
            queue_stats: {
                [key: string]: number;
            };
            /** Domain Stats */
            domain_stats: {
                [key: string]: number;
            };
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    list_projects_api_projects_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Projects"];
                };
            };
        };
    };
    summary_api_projects__project__summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Summary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    waves_api_projects__project__waves_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Waves"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_tasks_api_projects__project__tasks_get: {
        parameters: {
            query?: {
                status?: string | null;
                milestone?: string | null;
                domain?: string | null;
                parent_id?: string | null;
                /** @description substring of id or title */
                q?: string | null;
            };
            header?: never;
            path: {
                project: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Tasks"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_task_api_projects__project__tasks__task_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
                project: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_candidates_api_projects__project__tasks__task_id__candidates_get: {
        parameters: {
            query?: {
                run_id?: string | null;
            };
            header?: never;
            path: {
                task_id: string;
                project: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Candidates"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_runs_api_projects__project__runs_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                project: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Runs"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_api_projects__project__runs__run_id__get: {
        parameters: {
            query?: {
                event_limit?: number;
            };
            header?: never;
            path: {
                run_id: string;
                project: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    usage_api_projects__project__usage_get: {
        parameters: {
            query?: {
                group_by?: "role" | "model" | "provider" | "day";
            };
            header?: never;
            path: {
                project: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Usage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    metrics_api_projects__project__metrics_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Metrics"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_events_api_projects__project__events_get: {
        parameters: {
            query?: {
                since_rowid?: number | null;
                kind?: string | null;
                task_id?: string | null;
                run_id?: string | null;
                limit?: number;
            };
            header?: never;
            path: {
                project: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Events"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_jobs_api_projects__project__jobs_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Jobs"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_api_projects__project__jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
                project: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_log_api_projects__project__jobs__job_id__log_get: {
        parameters: {
            query?: {
                offset?: number;
            };
            header?: never;
            path: {
                job_id: string;
                project: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobLog"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
